### ISSUE TITLE
[✨ feature] Service details page

### ISSUE THREAD

**Issue by Fredkiss3** [zane-ops/zane-ops#186]
## Is your feature request related to a problem? Please describe.

We want to implement a details page for a docker service.

## Describe the solution you'd like

The page will be at `/project/{project_slug}/services/docker/{service_slug}`.

The page will be presented in the design provided in the next section. In the header we will have the slug of the service its image and its first URL (if it has one), if there is more than one URL for the service, we need to show a badge indicating the number of URLs, that badge should be a link redirecting the user to `/project/{project_slug}/services/docker/{service_slug}/settings#urls`.

On the right side of the header, there will be a `deploy` button always visible and a `{n} unapplied changes` that will be visible only when there are unapplied changes i.e `n` > 0.

In the body of the page, you can see the list of deployments : 
- There is a row with two inputs : `select date range` & `status` for filtering the list of deployments per date of deployment and status, these fields should be the same as how vercel works (see screenshot in the next section)
- The deployments returned from the API are shown from the most recent to the least recent. 
- Each deployment has different states which need to be represented in different background colors :
   | status   | description   |  color | 
   |---|---|---|
   |  QUEUED | a new deployment that has just been issued   |  gray |  
   |  CANCELLED | a deployment that have been cancelled from the UI   |  gray |  
   |  FAILED | a failed deployment  |  red |  
   |  PREPARING | The deployment is running and creating docker ressources  |  blue |  
   |  STARTING | The deployment is starting the containers for the service  |  blue |  
   |  RESTARTING | The deployment is starting the containers for the service   |  blue |  
   |  HEALTHY | The deployment is running without a problem  |  green |  
   |  UNHEALTHY | The deployment is having issues which require the user's attention  |  red |  
   |  REMOVED | The resources for deployment have been deleted (for older deployment) | gray |  
   |  SLEEPING | The service for the deployment is sleeping  |  orange |  
- The deployments should be grouped in different sections :
  - Only one deployment should be in the `current` section, and that deployment have the property of `is_current_production=true`
  - Group deployments with the status `QUEUED`, `PREPARING`, `STARTING` & `RESTARTING` in the `new` section as they represent the new deployments we issued but that haven't finished yet
  - Group the rest of the deployments in the `previous` section, as they represent all the previous deployments that no longer represent the status of the status of the service
  - Note that if there is no `new` deployments, the section should not be shown at all, same for `previous` deployments
- The deployments needs to be refreshed every 5 seconds (like we do on the other pages)
- The deployments duration shown in the UI should be `deployment.finished_at - deployment.started_at`, but for new deployments, `finished_at` & `started_at` can be null, in that case, if there is no started at, it should show a `-` (hyphen), if there is a `started_at` but no `finished_at`, it should show a timer component that updates every second starting from the `queued_at` time  with a spinner on the side : 
   ![ScreenRecording_08-04-2024 20-16-28_1](https://github.com/user-attachments/assets/89dbbf6e-52d4-46f0-8ef0-79ee0f50ea84)

- There should be a `load more` button to load more deployments, loading more deployments should append the deployments in the deployment list, to achieve this, we can use use [infinite queries from React Query](https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries) 
- Clicking on the `DEPLOY` button should invoke the deploy endpoint : https://zane.fredkiss.dev/docs/api-reference/openapi/#/tag/projects/PUT/api/projects/{project_slug}/deploy-service/docker/{service_slug}/

## Additional context

- We get the urls from the property : `service.urls`, each url should be formatted as `https://{url.domain}{url.base_path}`.
- To get the unapplied changes, see `service.unapplied_changes` returned by the service endpoint.
- Vercel inspiration for the list of deployment
   <img width="1277" alt="image" src="https://github.com/user-attachments/assets/7d059442-c5db-4849-8999-b110cda52808">
  <img width="325" alt="image" src="https://github.com/user-attachments/assets/04965b4b-3bd5-425c-bc58-8222043e073a">
- React Query Infinite queries :
  - https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries
  - https://tanstack.com/query/latest/docs/framework/react/reference/useInfiniteQuery#useinfinitequery

### Endpoints

- Get service details : https://zane.fredkiss.dev/docs/api-reference/openapi/#/tag/projects/GET/api/projects/{project_slug}/service-details/docker/{service_slug}/
- Get deployments for a service : https://zane.fredkiss.dev/docs/api-reference/openapi/#/tag/projects/GET/api/projects/{project_slug}/service-details/docker/{service_slug}/deployments/

### Wireframes

![image](https://github.com/user-attachments/assets/fc93b81d-5169-4131-8916-00bf3a672a62)
![image](https://github.com/user-attachments/assets/b9cbddf1-2208-4fa6-8fe5-4d3c09c1f1c2)
![image](https://github.com/user-attachments/assets/8dae1e16-92bf-47e1-8518-1c93bb0fd8b5)

---
- [ ] Are you willing to make a PR for this ?

**Comment by mo-cherif** [comment]
Nice
